[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string]$OpenApi,
    [Parameter(Mandatory = $true)][ValidatePattern('^[A-Za-z0-9_-]+$')][string]$Name,
    [Parameter(Mandatory = $true)][string]$BaseUrl,
    [string]$Root = (Split-Path $PSScriptRoot -Parent),
    [string]$StoryProfile = 'parallel-crud',
    [int]$Seed = 2,
    [ValidateRange(1, 8)][int]$LogicalProcesses = 1,
    [ValidateRange(1, 8)][int]$InstancesPerEntity = 1,
    [string]$ReviewZip = (Join-Path $env:USERPROFILE 'Downloads\generic_generator_review.zip'),
    [switch]$ResourceMaps,
    [string]$RelationshipProfile,
    [switch]$CompileRelationships,
    [string]$RelationshipRuntime
)
$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'Resolve-Python.ps1')
$python = Get-StudyPython
$contract = (Resolve-Path -LiteralPath $OpenApi).Path
if ($RelationshipProfile) { $RelationshipProfile = (Resolve-Path -LiteralPath $RelationshipProfile).Path }
if ($RelationshipRuntime) { $RelationshipRuntime = (Resolve-Path -LiteralPath $RelationshipRuntime).Path }
if ($CompileRelationships -and (-not $RelationshipProfile -or -not $RelationshipRuntime)) { throw 'Compilation requires RelationshipProfile and RelationshipRuntime.' }
$studyRoot = [IO.Path]::GetFullPath($Root)
$generatorRoot = Join-Path $studyRoot 'generic-generator'
$project = Join-Path $studyRoot ('provengo\generic-' + $Name + '-' + [guid]::NewGuid().ToString('N').Substring(0, 12))
$jsRoot = Join-Path $project 'spec\js'
New-Item -ItemType Directory -Path $jsRoot -Force | Out-Null
$arguments = @($python.Prefix) + @('-m', 'generator_v56', 'generate',
    '--openapi', $contract, '--output', $jsRoot, '--name', $Name,
    '--base-url', $BaseUrl, '--seed', [string]$Seed, '--story-profile', $StoryProfile,
    '--logical-processes', [string]$LogicalProcesses, '--instances-per-entity', [string]$InstancesPerEntity)
if ($ResourceMaps) { $arguments += '--resource-maps' }
if ($RelationshipProfile) { $arguments += @('--relationship-profile', $RelationshipProfile) }
if ($CompileRelationships) { $arguments += '--compile-relationships' }
if ($RelationshipRuntime) { $arguments += @('--relationship-runtime', $RelationshipRuntime) }
Push-Location $generatorRoot
try {
    & $python.Exe @arguments
    if ($LASTEXITCODE -ne 0) { throw 'Original generic generator failed.' }
} finally { Pop-Location }
foreach ($report in @('generation_report.json', 'dependency_graph.json', 'resource_catalog.json',
                     'operation_map.json', 'relationship_map.json', 'relationship_scenario_plan.json', 'relationship_compilation.json')) {
    if (Test-Path -LiteralPath (Join-Path $jsRoot $report)) {
        Move-Item -LiteralPath (Join-Path $jsRoot $report) -Destination (Join-Path $project $report)
    }
}
$stories = Get-Content -LiteralPath (Join-Path $jsRoot ('stories.' + $Name + '.js')) -Raw
if ($stories -match '\bsvc\s*\.\s*(get|post|put|patch|delete|head|options)\s*\(') {
    throw 'Direct HTTP was found in generated stories.'
}
New-Item -ItemType Directory -Path (Join-Path $project 'config') -Force | Out-Null
'version: 2' | Set-Content -LiteralPath (Join-Path $project 'config\provengo.yml') -Encoding ASCII
$readiness = [ordered]@{
    result = 'GENERIC_GENERATOR_STATIC_FILES_READY'; revision = 'resource-maps.1'
    contractSha256 = (Get-FileHash -LiteralPath $contract -Algorithm SHA256).Hash.ToLowerInvariant()
    storyProfile = $StoryProfile; logicalProcesses = $LogicalProcesses
    instancesPerEntity = $InstancesPerEntity; directHttpInStories = $false
    serverRequestsSent = 0; sampled = $false; liveAccepted = $false
    resourceMapsRequested = [bool]($ResourceMaps -or $RelationshipProfile)
    relationshipPlanRequested = [bool]$RelationshipProfile
    compiledRelationships = [bool]$CompileRelationships
}
if ($CompileRelationships) { $readiness.revision = 'compiled-relationships.1' }
$readiness | ConvertTo-Json -Depth 6 | Set-Content -LiteralPath (Join-Path $project 'readiness.json') -Encoding UTF8
New-Item -ItemType Directory -Path (Split-Path ([IO.Path]::GetFullPath($ReviewZip)) -Parent) -Force | Out-Null
Compress-Archive -Path (Join-Path $project '*') -DestinationPath $ReviewZip -Force
Write-Host $readiness.result
Write-Host ('Generated project: ' + $project)
Write-Host ('Review ZIP: ' + $ReviewZip)
Write-Host 'Generated by the original generic generator. Sampling and live acceptance are pending.'
if ($CompileRelationships) {
    Write-Host 'Relationship tasks are compiled into generated actors. Native sampling and live execution are pending.'
} elseif ($RelationshipProfile) {
    Write-Host 'Relationship scenario plan is review-only. Generated JS retains the legacy story schedule.'
}
