// @provengo summon rest
// Explicit stage1 profile; all domain HTTP delegated to the recording transport.
var stage1Service=new RESTSession("@{getEnv('SBT_STAGE1_BRIDGE')}");
function stage1Callback(){
var source="if(typeof Packages!=='undefined'){Packages.org.mozilla.javascript.Context.getCurrentContext().initStandardObjects(Packages.org.mozilla.javascript.ScriptableObject.getTopLevelScope(this));}"+
"var data=JSON.parse(response.body);if(response.code!==200||data.ok!==true){pvg.fail('Stage1 transport/oracle failure');throw new Error('Stage1 step failed');}"+
"if(data.result&&data.result.status==='STAGE1_NATIVE_RECEIPT'){pvg.rtv.set('stage1_receipt',JSON.stringify(data.result));pvg.success('STAGE1_NATIVE_RECEIPT '+JSON.stringify(data.result));}";
if(typeof Packages!=='undefined'){var scope=new Packages.org.mozilla.javascript.NativeObject();(new Packages.org.mozilla.javascript.ClassCache()).associate(scope);return Packages.org.mozilla.javascript.Context.getCurrentContext().compileFunction(scope,"function(response,arguments){"+source+"}","stage1-callback",1,null);}
return new Function('response',source);}
function stage1_start(){stage1Service.post("/sbt/step/start",{headers:{"X-SBT-Key":"@{getEnv('SBT_STAGE1_KEY')}","Content-Type":"application/json"},body:"{}",expectedResponseCodes:[200],callback:stage1Callback()});}
function stage1_create_T(){stage1Service.post("/sbt/step/create_T",{headers:{"X-SBT-Key":"@{getEnv('SBT_STAGE1_KEY')}","Content-Type":"application/json"},body:"{}",expectedResponseCodes:[200],callback:stage1Callback()});}
function stage1_read_T(){stage1Service.post("/sbt/step/read_T",{headers:{"X-SBT-Key":"@{getEnv('SBT_STAGE1_KEY')}","Content-Type":"application/json"},body:"{}",expectedResponseCodes:[200],callback:stage1Callback()});}
function stage1_rename_T(){stage1Service.post("/sbt/step/rename_T",{headers:{"X-SBT-Key":"@{getEnv('SBT_STAGE1_KEY')}","Content-Type":"application/json"},body:"{}",expectedResponseCodes:[200],callback:stage1Callback()});}
function stage1_create_U(){stage1Service.post("/sbt/step/create_U",{headers:{"X-SBT-Key":"@{getEnv('SBT_STAGE1_KEY')}","Content-Type":"application/json"},body:"{}",expectedResponseCodes:[200],callback:stage1Callback()});}
function stage1_read_U(){stage1Service.post("/sbt/step/read_U",{headers:{"X-SBT-Key":"@{getEnv('SBT_STAGE1_KEY')}","Content-Type":"application/json"},body:"{}",expectedResponseCodes:[200],callback:stage1Callback()});}
function stage1_create_Y(){stage1Service.post("/sbt/step/create_Y",{headers:{"X-SBT-Key":"@{getEnv('SBT_STAGE1_KEY')}","Content-Type":"application/json"},body:"{}",expectedResponseCodes:[200],callback:stage1Callback()});}
function stage1_read_Y(){stage1Service.post("/sbt/step/read_Y",{headers:{"X-SBT-Key":"@{getEnv('SBT_STAGE1_KEY')}","Content-Type":"application/json"},body:"{}",expectedResponseCodes:[200],callback:stage1Callback()});}
function stage1_rename_Y(){stage1Service.post("/sbt/step/rename_Y",{headers:{"X-SBT-Key":"@{getEnv('SBT_STAGE1_KEY')}","Content-Type":"application/json"},body:"{}",expectedResponseCodes:[200],callback:stage1Callback()});}
function stage1_upload_A(){stage1Service.post("/sbt/step/upload_A",{headers:{"X-SBT-Key":"@{getEnv('SBT_STAGE1_KEY')}","Content-Type":"application/json"},body:"{}",expectedResponseCodes:[200],callback:stage1Callback()});}
function stage1_wait_A(){stage1Service.post("/sbt/step/wait_A",{headers:{"X-SBT-Key":"@{getEnv('SBT_STAGE1_KEY')}","Content-Type":"application/json"},body:"{}",expectedResponseCodes:[200],callback:stage1Callback()});}
function stage1_read_A(){stage1Service.post("/sbt/step/read_A",{headers:{"X-SBT-Key":"@{getEnv('SBT_STAGE1_KEY')}","Content-Type":"application/json"},body:"{}",expectedResponseCodes:[200],callback:stage1Callback()});}
function stage1_checksum_A(){stage1Service.post("/sbt/step/checksum_A",{headers:{"X-SBT-Key":"@{getEnv('SBT_STAGE1_KEY')}","Content-Type":"application/json"},body:"{}",expectedResponseCodes:[200],callback:stage1Callback()});}
function stage1_link_A(){stage1Service.post("/sbt/step/link_A",{headers:{"X-SBT-Key":"@{getEnv('SBT_STAGE1_KEY')}","Content-Type":"application/json"},body:"{}",expectedResponseCodes:[200],callback:stage1Callback()});}
function stage1_rename_A(){stage1Service.post("/sbt/step/rename_A",{headers:{"X-SBT-Key":"@{getEnv('SBT_STAGE1_KEY')}","Content-Type":"application/json"},body:"{}",expectedResponseCodes:[200],callback:stage1Callback()});}
function stage1_detach_A(){stage1Service.post("/sbt/step/detach_A",{headers:{"X-SBT-Key":"@{getEnv('SBT_STAGE1_KEY')}","Content-Type":"application/json"},body:"{}",expectedResponseCodes:[200],callback:stage1Callback()});}
function stage1_reattach_A(){stage1Service.post("/sbt/step/reattach_A",{headers:{"X-SBT-Key":"@{getEnv('SBT_STAGE1_KEY')}","Content-Type":"application/json"},body:"{}",expectedResponseCodes:[200],callback:stage1Callback()});}
function stage1_upload_B(){stage1Service.post("/sbt/step/upload_B",{headers:{"X-SBT-Key":"@{getEnv('SBT_STAGE1_KEY')}","Content-Type":"application/json"},body:"{}",expectedResponseCodes:[200],callback:stage1Callback()});}
function stage1_wait_B(){stage1Service.post("/sbt/step/wait_B",{headers:{"X-SBT-Key":"@{getEnv('SBT_STAGE1_KEY')}","Content-Type":"application/json"},body:"{}",expectedResponseCodes:[200],callback:stage1Callback()});}
function stage1_read_B(){stage1Service.post("/sbt/step/read_B",{headers:{"X-SBT-Key":"@{getEnv('SBT_STAGE1_KEY')}","Content-Type":"application/json"},body:"{}",expectedResponseCodes:[200],callback:stage1Callback()});}
function stage1_checksum_B(){stage1Service.post("/sbt/step/checksum_B",{headers:{"X-SBT-Key":"@{getEnv('SBT_STAGE1_KEY')}","Content-Type":"application/json"},body:"{}",expectedResponseCodes:[200],callback:stage1Callback()});}
function stage1_link_B(){stage1Service.post("/sbt/step/link_B",{headers:{"X-SBT-Key":"@{getEnv('SBT_STAGE1_KEY')}","Content-Type":"application/json"},body:"{}",expectedResponseCodes:[200],callback:stage1Callback()});}
function stage1_merge_B(){stage1Service.post("/sbt/step/merge_B",{headers:{"X-SBT-Key":"@{getEnv('SBT_STAGE1_KEY')}","Content-Type":"application/json"},body:"{}",expectedResponseCodes:[200],callback:stage1Callback()});}
function stage1_label_B(){stage1Service.post("/sbt/step/label_B",{headers:{"X-SBT-Key":"@{getEnv('SBT_STAGE1_KEY')}","Content-Type":"application/json"},body:"{}",expectedResponseCodes:[200],callback:stage1Callback()});}
function stage1_upload_C(){stage1Service.post("/sbt/step/upload_C",{headers:{"X-SBT-Key":"@{getEnv('SBT_STAGE1_KEY')}","Content-Type":"application/json"},body:"{}",expectedResponseCodes:[200],callback:stage1Callback()});}
function stage1_wait_C(){stage1Service.post("/sbt/step/wait_C",{headers:{"X-SBT-Key":"@{getEnv('SBT_STAGE1_KEY')}","Content-Type":"application/json"},body:"{}",expectedResponseCodes:[200],callback:stage1Callback()});}
function stage1_read_C(){stage1Service.post("/sbt/step/read_C",{headers:{"X-SBT-Key":"@{getEnv('SBT_STAGE1_KEY')}","Content-Type":"application/json"},body:"{}",expectedResponseCodes:[200],callback:stage1Callback()});}
function stage1_checksum_C(){stage1Service.post("/sbt/step/checksum_C",{headers:{"X-SBT-Key":"@{getEnv('SBT_STAGE1_KEY')}","Content-Type":"application/json"},body:"{}",expectedResponseCodes:[200],callback:stage1Callback()});}
function stage1_link_C(){stage1Service.post("/sbt/step/link_C",{headers:{"X-SBT-Key":"@{getEnv('SBT_STAGE1_KEY')}","Content-Type":"application/json"},body:"{}",expectedResponseCodes:[200],callback:stage1Callback()});}
function stage1_merge_C(){stage1Service.post("/sbt/step/merge_C",{headers:{"X-SBT-Key":"@{getEnv('SBT_STAGE1_KEY')}","Content-Type":"application/json"},body:"{}",expectedResponseCodes:[200],callback:stage1Callback()});}
function stage1_label_C(){stage1Service.post("/sbt/step/label_C",{headers:{"X-SBT-Key":"@{getEnv('SBT_STAGE1_KEY')}","Content-Type":"application/json"},body:"{}",expectedResponseCodes:[200],callback:stage1Callback()});}
function stage1_upload_D(){stage1Service.post("/sbt/step/upload_D",{headers:{"X-SBT-Key":"@{getEnv('SBT_STAGE1_KEY')}","Content-Type":"application/json"},body:"{}",expectedResponseCodes:[200],callback:stage1Callback()});}
function stage1_wait_D(){stage1Service.post("/sbt/step/wait_D",{headers:{"X-SBT-Key":"@{getEnv('SBT_STAGE1_KEY')}","Content-Type":"application/json"},body:"{}",expectedResponseCodes:[200],callback:stage1Callback()});}
function stage1_read_D(){stage1Service.post("/sbt/step/read_D",{headers:{"X-SBT-Key":"@{getEnv('SBT_STAGE1_KEY')}","Content-Type":"application/json"},body:"{}",expectedResponseCodes:[200],callback:stage1Callback()});}
function stage1_checksum_D(){stage1Service.post("/sbt/step/checksum_D",{headers:{"X-SBT-Key":"@{getEnv('SBT_STAGE1_KEY')}","Content-Type":"application/json"},body:"{}",expectedResponseCodes:[200],callback:stage1Callback()});}
function stage1_link_D(){stage1Service.post("/sbt/step/link_D",{headers:{"X-SBT-Key":"@{getEnv('SBT_STAGE1_KEY')}","Content-Type":"application/json"},body:"{}",expectedResponseCodes:[200],callback:stage1Callback()});}
function stage1_upload_V(){stage1Service.post("/sbt/step/upload_V",{headers:{"X-SBT-Key":"@{getEnv('SBT_STAGE1_KEY')}","Content-Type":"application/json"},body:"{}",expectedResponseCodes:[200],callback:stage1Callback()});}
function stage1_wait_V(){stage1Service.post("/sbt/step/wait_V",{headers:{"X-SBT-Key":"@{getEnv('SBT_STAGE1_KEY')}","Content-Type":"application/json"},body:"{}",expectedResponseCodes:[200],callback:stage1Callback()});}
function stage1_label_V(){stage1Service.post("/sbt/step/label_V",{headers:{"X-SBT-Key":"@{getEnv('SBT_STAGE1_KEY')}","Content-Type":"application/json"},body:"{}",expectedResponseCodes:[200],callback:stage1Callback()});}
function stage1_final_graph(){stage1Service.post("/sbt/step/final_graph",{headers:{"X-SBT-Key":"@{getEnv('SBT_STAGE1_KEY')}","Content-Type":"application/json"},body:"{}",expectedResponseCodes:[200],callback:stage1Callback()});}
function stage1_finish(){stage1Service.post("/sbt/step/finish",{headers:{"X-SBT-Key":"@{getEnv('SBT_STAGE1_KEY')}","Content-Type":"application/json"},body:"{}",expectedResponseCodes:[200],callback:stage1Callback()});}
